default: &default
  adapter: mysql2
  host: localhost
  pool: 5
  timeout: 5000
  encoding: utf8mb4
  colation: utf8mb4_unicode_ci

development:
  <<: *default
  database: mickleberry_development

test:
  <<: *default
  database: mickleberry_test

production:
  <<: *default
  database: mickleberry_production
