default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: mickleberry_development

test:
  <<: *default
  database: mickleberry_test

production:
  <<: *default
  database: mickleberry_production
